# Задание 1

In [142]:
string_01 = "Mama, just killed a man, put a gun against his head, pulled my trigger, now he's dead. Mama, life had just begun, but now I've gone and thrown it all away. Mama, ooh (any way the wind blows), didn't mean to make you cry. If I'm not back again this time tomorrow carry on, carry on as if nothing really matters"

In [143]:
print(len(string_01.strip()))

309


In [144]:
string_by_word = string_01.strip().split()
print(string_by_word)

['Mama,', 'just', 'killed', 'a', 'man,', 'put', 'a', 'gun', 'against', 'his', 'head,', 'pulled', 'my', 'trigger,', 'now', "he's", 'dead.', 'Mama,', 'life', 'had', 'just', 'begun,', 'but', 'now', "I've", 'gone', 'and', 'thrown', 'it', 'all', 'away.', 'Mama,', 'ooh', '(any', 'way', 'the', 'wind', 'blows),', "didn't", 'mean', 'to', 'make', 'you', 'cry.', 'If', "I'm", 'not', 'back', 'again', 'this', 'time', 'tomorrow', 'carry', 'on,', 'carry', 'on', 'as', 'if', 'nothing', 'really', 'matters']


In [145]:
letter = input('letter: ')

letter: t


In [146]:
print(letter)

t


In [147]:
words_result = []
def words_by_letter():
    for word in string_by_word:
        if list(word)[-1] == letter:
            print(word)

In [148]:
print(words_by_letter())

just
put
against
just
but
it
didn't
not
None


# Задание 2

In [173]:
import string
import random

In [174]:
def randomString(stringLength=6):
    """Generate a random string of fixed length """
    digits = string.digits
    my_digit = '3'
    return ''.join(random.choice(digits + my_digit) for i in range(stringLength))

In [175]:
print(randomString())

139962


In [ ]:
# но данный код не каждый раз генерит последовательность, включающую 3, - не знаю, как изменить

# Задание 3

In [154]:
list_01 = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610]

In [155]:
elements = []
for element in list_01:
    if element >=10:
        if element <=100:
            elements.append(element)
print(sum(elements))

212


# Задание 4

In [98]:
students = [
["0001", "Антонов", "Антон", "Игоревич", "20.08.2009",
"БСТ161"],
["1102", "Богов", "Артем", "Игоревич", "25.01.2010",
"БСТ162"],
["0333", "Глаголева", "Анастасия", "Николаевна", "11.07.2009", "БСТ163"],
["4004", "Степанова", "Наталья", "Александровна", "13.02.2008", "БСТ161"],
["0045", "Боков", "Игорь", "Харитонович", "02.06.2009", "БСТ161"],
["0096", "Васильков", "Валентин", "Сергеевич", "20.03.2009", "БСТ164"],
["0607", "Сиропова", "Виолетта", "Эдуардовна", "28.05.2010", "БСТ162"],
["0309", "Шафутинский", "Михаил", "Михайлович", "03.09.2007", "БСТ163"]
]

In [99]:
# 1. Преобразуйте данные таким образом, чтобы они были представлены в виде словаря, 
# в котором ключами являются номера студентов, а значениями — список из других данных о студентах.
# 2. Напишите функцию, которая принимает в качестве аргумента номер студента и новый номер группы и 
# позволяет изменить номер группы этого студента на новый.
# 3. Напишите функцию, которая принимает номер группы и выводит список (фамилии, имена, отчества) всех 
# студентов этой группы.

In [100]:
students_dict = {}

In [106]:
for i in students:
    students_dict[i[0]] = [i[1], i[2], i[3], i[4], i[5]]

In [107]:
print(students_dict)

{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162'], '0333': ['Глаголева', 'Анастасия', 'Николаевна', '11.07.2009', 'БСТ163'], '4004': ['Степанова', 'Наталья', 'Александровна', '13.02.2008', 'БСТ161'], '0045': ['Боков', 'Игорь', 'Харитонович', '02.06.2009', 'БСТ161'], '0096': ['Васильков', 'Валентин', 'Сергеевич', '20.03.2009', 'БСТ164'], '0607': ['Сиропова', 'Виолетта', 'Эдуардовна', '28.05.2010', 'БСТ162'], '0309': ['Шафутинский', 'Михаил', 'Михайлович', '03.09.2007', 'БСТ163']}


In [176]:
# дальше застряла...

# Задание 5

In [177]:
matrix = [ [0,1,2,4,8], [6,2,2,1,9], [3,3,3,3,3], [4,6,7,1,2], [5,7,3,4,0] ]

In [178]:
x = np.matrix(matrix)

In [179]:
print(x)

[[0 1 2 4 8]
 [6 2 2 1 9]
 [3 3 3 3 3]
 [4 6 7 1 2]
 [5 7 3 4 0]]


In [180]:
x.sum()

89

In [181]:
max_column = x.sum(axis = 0)
print(max_column)

[[18 19 17 13 22]]


In [182]:
print(type(max_column))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [183]:
y = max_column.tolist()
print(type(y))

<class 'list'>


In [184]:
for element in y:
    print(max(element))

22
